# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['camera_daemon.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config.yaml', '.'),
        ('source', 'source'),
        ('temp', 'temp'),
    ],
    hiddenimports=[
        'tkinter',
        'PIL',
        'PIL.Image',
        'google.generativeai',
        'anthropic',
        'openai',
        'sounddevice',
        'scipy.io.wavfile',
        'playsound',
        'cv2',
        'yaml',
        'numpy',
        'requests',
        'image_utils',
        'ai_backends',
        'email_notify',
        'line_notify_module',
        'phone_notify_module',
        'alarm_sound_module',
        'alarm_clock_module',
        'startup_dialog',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='CameraGPT',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
